# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Monster ASP Deployment

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Web Deploy Action
      uses: zenoskongfu/server_deploy@1.0.1
      with:
        source_dir: ./publish
        server_key: ${{ secrets.SERVER_PASSWORD }}
        server_user: ${{ secrets.SERVER_USERNAME }}
        server_host: ${{ secrets.SERVER_HOSTNAME }}
          

    # - name: Deploy via WebDeploy
    #   uses: rasmusbuchholdt/simply-web-deploy@2.1.0
    #   with:
    #     website-name: ${{ secrets.WEB_APP_URL }}
    #     server-computer-name: ${{ secrets.SERVER_HOSTNAME }}
    #     server-username: ${{ secrets.SERVER_USERNAME }}
    #     server-password: ${{ secrets.SERVER_PASSWORD }}
    #     source-path: './publish'
