# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Monster ASP Deployment

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install wasm-tools workload
      run: dotnet workload install wasm-tools
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Publish
      run: |
          dotnet publish `
            --configuration Release `
            --output ./publish `

    - name: Upload publish artifact
      uses: actions/upload-artifact@v4
      with:
          name: blazor-publish
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download publish artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-publish
          path: ./publish
      - name: Deploy via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.SITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_URL }}
          server-username: ${{ secrets.USERNAME }}
          server-password: ${{ secrets.PASSWORD }}
          source-path: './publish'
